"""
Buffett' value investing

1. Understand the business
    Finding companies to examine:
        1. Where do I spend my time?
        2. What do I spend money on?

2. Look for a competitive advantage
    MOAT:
        https://www.investopedia.com/ask/answers/05/economicmoat.asp
        https://www.cnbc.com/2018/05/07/warren-buffett-believes-this-is-the-
            most-important-thing-to-find-in-a-business.html
        https://mywallst.com/blog/4-ways-to-find-economic-moats-like-warren-
            buffett/
        https://stablebread.com/how-to-identify-an-economic-moat/

3. Check the management team
    - Manager track record 10 / 15 years / Promises & results
    - https://investor.apple.com/investor-relations/default.aspx

4. Valuation and margin of safety
    - https://corporatefinanceinstitute.com/resources/knowledge/
        finance/margin-of-safety-formula/
    - https://www.liberatedstocktrader.com/margin-of-safety/
    - Discounted Cash Flow, Dividend Growth Model

Info source:
    https://www.youtube.com/watch?v=dWDPMD_rCY0
    https://profitful.online/available-courses
    https://www.gurufocus.com/stock/FB/dcf
    https://www.youtube.com/watch?v=l-T-Vyk2txc

    Data:
        https://roic.ai/financials/IRM
        https://uk.finance.yahoo.com/

    How to Calculate the Intrinsic Value of a Stock:
        https://www.youtube.com/watch?v=l-T-Vyk2txc
"""


# Phil Town
# https://ignorethestreet.com/phil-town-big-five-numbers/ - 5 big numbers
# To check if a company is good
# https://www.youtube.com/watch?v=5_Rt1Onv0C4

# Just calculate fair price if passes 5 big numbers


def intrinsic_value_phil_town(
    eps_ttm, growth_rate, p_e_ratio, margin_safety, minimum_return_rate
):
    """The fair value of the business. What the business is really worth to us.

    The intrisic value is the present value of all future cash flows, added together.

    `The intrinsic value of any stock, bond or business today is determined by the cash
    inflows and outflows, discounted at an appropriate interest rate, that can be
    expected to occur during the remaining life of the asset`, John Burr Williams`

    What we need to know?
        1 - How much cash will the business make for you in the future?
        2 - What are the future cash flows worth to you right now?

    Example:
        >>> from investment_strategies.value_investing import intrinsic_value_phil_town
        >>> print(intrinsic_value_phil_town())
        {'fair_value': 152.77203681740585, 'margin_safety': 76.38601840870292}

    # TODO: Update documentation
    """

    # https://www.youtube.com/watch?v=nX2DcXOrtuo - Apple Stock Example
    # https://www.msn.com/en-gb/money/stockdetails/analysis/fi-a1mou2?ocid=ansMSNMoney11

    # Earnings Next 10 years
    earnings_next_10_years = [eps_ttm]
    for year in range(0, 9):  # Assume 0 as year 1
        previous_earnings = earnings_next_10_years[year]

        earnings_next_10_years.append(
            previous_earnings + (previous_earnings * growth_rate)
        )

    # Shares Price next 10 years
    shares_price_next_10_years = []
    for earnings_year in earnings_next_10_years:
        shares_price_next_10_years.append(earnings_year * p_e_ratio)

    # Fair Value
    reversed_shares_price_next_10_years = shares_price_next_10_years[::-1]
    afford_to_pay_today = [reversed_shares_price_next_10_years[0]]
    for year in range(0, 9):  # Assume 0 as year 1
        afford_to_pay = afford_to_pay_today[year] / (1 + minimum_return_rate)

        afford_to_pay_today.append(afford_to_pay)

    reversed_afford_to_pay_today = afford_to_pay_today[::-1]

    fair_value = reversed_afford_to_pay_today[0]

    return {"fair_value": fair_value, "margin_safety": fair_value * margin_safety}


def calculate_free_cash_flow(operating_cash_flow, total_capital_expenditure):
    """Free Cash Flow = Operating Cash Flow / Total Capital Expenditure

    Operating Cash Flow: A measure of the amount of cash generated by a company's
      normal business operations

    Total Capital Expenditure: CapEx that is necessary for the company to
      continue operating in its current form, and grow the business

    Operating Cash Flow
        Yahoo - Net cash provided by operating activities:
            https://uk.finance.yahoo.com/quote/AAPL/cash-flow?p=AAPL&.tsrc=fin-srch
        Roic.ai - Cash provided by operating activities
            https://roic.ai/financials/AAPL

    Total Capital Expenditure
        Yahoo - Capital expenditure
            https://uk.finance.yahoo.com/quote/AAPL/cash-flow?p=AAPL&.tsrc=fin-srch
        Roic.ai - Cash provided by operating activities
            https://roic.ai/financials/AAPL
    """
    return operating_cash_flow - total_capital_expenditure


def calculate_margin_safety():
    """The function of the margin of safety is, in essence, that of rendering
    unnecessary an accurate estimate of the future, Benjamin Graham.
    """
    pass


def intrinsic_value_warren():
    """https://www.youtube.com/watch?v=EuEskF9mOtE
    """
    # TODO: Implement
    pass
